version: '3.8'
services:
  app:
    image: gontarskiadrian/app_new:latest
    ports: 
    - "3000:3000"
    - "27017:27017"
    environment:
      - MONGO_URL=mongodb://mongo:27017/movies
    volumes:
      - mongo-data:/data/db
 
 
volumes:
  mongo-data:
