name: CI for APP
 
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main] 
 
jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 20.x]
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Instalacja Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
 
    - name: Instalacja dependencji
      run: npm install
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
 
    - name: Verify WORKDIR in backend image
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/backend:latest pwd
 
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
 
    - name: Verify SSH key
      run: |
        cat ~/.ssh/id_rsa
        ls -la ~/.ssh/
 
    - name: Copy backend files to server
      run: |
        scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./backend/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/docker/app_new
 
    - name: Copy docker-compose.yml to server
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/docker/app_new
 
    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          # sudo chmod +x /usr/local/bin/docker-compose
          # sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          cd /home/docker/app_new
          docker-compose -f /home/docker/app_new/docker-compose.yml up -d
        EOF
